### ISSUE TITLE
Update Remote Assignment Repository on File Modifications

### ISSUE THREAD

**Issue by maxsmith271346** [tamu-edu-students/csce-606-autograder-frontend#14]
An `Assignment`'s associated remote repository must be immediately updated with any change made to the local clone to ensure that Gradescope is using the most recent tests.

Acceptance criteria in: `features/update_remote_repository.feature`

**Comment by saksham1919** [comment]
Remote repo update Feature when there are file modifications is done. Code changes done in Assignments Model and Controller classes for Assignments. Completed RSpec testing and Cucumber scenarios along with step definitions.

The following PR is created/ merged/ deployed:
https://github.com/tamu-edu-students/csce-606-autograder-frontend/pull/34
