### ISSUE TITLE
Logout System

### ISSUE THREAD

**Issue by riddhighate-tamu** [tamu-edu-students/csce-606-autograder-frontend#55]
Link the already existing `session#destroy` logout route to `Logout` button in navigation bar. Ensure that the session is closed and redirect the user to the `Login` page on logout.

**Comment by saksham1919** [comment]
Logout functionality and session management for the application is implemented and fully tested with 100% passing RSpec and Cucumber scenarios along with complete code coverage.
Following PR was raised and merged to the main:
https://github.com/tamu-edu-students/csce-606-autograder-frontend/pull/89
