### ISSUE TITLE
Navigation Bar

### ISSUE THREAD

**Issue by riddhighate-tamu** [tamu-edu-students/csce-606-autograder-frontend#56]
Add a navigation bar at the top of all the views that lets the users browse quickly to other pages of the application. The main links on the navigation bar : `app icon`, `app name`, `course dashboard`, `manage users`, and `logout`.

**Comment by saksham1919** [comment]
Navigation Bar functionality built and tested with RSpec and Cucumber. 
Following PR was raised and merged to the main:
https://github.com/tamu-edu-students/csce-606-autograder-frontend/pull/89
