### ISSUE TITLE
Test Case Groupings Model

### ISSUE THREAD

**Issue by riddhighate-tamu** [tamu-edu-students/csce-606-autograder-frontend#57]
The related tests need to be combined into a single group that maintains the relation between these tests. Create a `TestGroup` model through `has_many :through` association in `Assignment `model for `Test` through `TestGroup`.

**Comment by maxsmith271346** [comment]
@riddhighate-tamu @yaoya2618-dot I've begun this story, and I don't really think that it needs two people to be working on it
